### ISSUE TITLE
"in" and "nin" queries broken for empty Lists

### ISSUE THREAD

**Issue by adamalix** [foursquare/slashem#17]
"in" and "nin" queries are broken for empty lists and spit out a nasty exception; this should be fixed but queries should be guarded against using empty lists until this is fixed.

**Comment by holdenk** [comment]
Going to take a look at this..

**Comment by holdenk** [comment]
This seems to  be fixed, I've added a test case for this 0.9.14

**Comment by adamalix** [comment]
This is still broken.  There is a test case in ElasticQueryTest.scala: 308 that blows up.

**Comment by holdenk** [comment]
Are you sure? I could have sworn the tests passed when I ran them. I will
take a look tomorrow.
On May 9, 2012 9:26 PM, "Adam Alix" <
reply@reply.github.com>
wrote:

**Comment by adamalix** [comment]
Check the branch that you're on.  This fails on master.

**Comment by adamalix** [comment]
We should have a discussion offline about whether or not this is a relevant test case.
