### ISSUE TITLE
using as library dependency

### ISSUE THREAD

**Issue by mads-hartmann** [foursquare/slashem#25]
Hi there, 

When I add slashem as a dependency (`"com.foursquare" %% "slashem" % "0.9.10"`) it isn't able to fetch all the libraries it needs. I get the following error:

```
error] {file:/Users/Mads/dev/projects/cataalog-web/}default-140763/*:update: sbt.ResolveException: unresolved dependency:   com.codahale#jerkson_2.8.1;0.1.4: not found
[error] download failed: javax.jms#jms;1.1!jms.jar
[error] download failed: com.sun.jdmk#jmxtools;1.2.1!jmxtools.jar
[error] download failed: com.sun.jmx#jmxri;1.2.1!jmxri.jar 
```

I've been able to fix it by declaring slashem as intransitive() and adding the dependencies manually for now.

**Comment by holdenk** [comment]
Another option is to add:

```
ivyXML := (
<dependencies>
 <exclude module="jmxtools"/>
 <exclude module="jmxri"/>
</dependencies>
)
```

Sadly these dependencies are pulled in from some of the deps (log4j) of Slashem and aren't published to the central maven.

**Comment by mads-hartmann** [comment]
Thanks, this is definitely a much, much prettier solution :) Maybe add it to the README?

**Comment by holdenk** [comment]
Good idea. We've got a few fixes/improvements we are working on right now, I'll give the documentation a once-over before we push the next version :)

**Comment by mads-hartmann** [comment]
Nice, seems like I picked a good time to start using Slashem :)
