### ISSUE TITLE
Multiple Cores

### ISSUE THREAD

**Issue by mads-hartmann** [foursquare/slashem#29]
Hi there, 

How do you deal with multiple cores? If I add the name of the core to the servers list 

```
def servers = List(Props.get("solr.host").open_! + "/books") // Ignore bad practice of .open_! here
```

then I get the following error 

```
java.lang.NumberFormatException: For input string: "8983/books"
```

How do I specific that it should use a specific core? 

Thanks,
Mads

**Comment by holdenk** [comment]
Oh hmm. We don't currently support multiple cores. I'll add that. (We use two cores, but only for indexing and swapping, we only ever query against the primary core).

**Comment by mads-hartmann** [comment]
Cool thanks :) 

As I'm new to Solr I don't know if what I'm doing makes sense. We have information about things like books, 
films, bans etc. so my plan was to create a core for each so they could use separate schemas.

**Comment by holdenk** [comment]
That sounds reasonable. Our data just happens to be large enough that we have separate solr's for each schema, so our multi-core configuration is only used as an indexing hack

**Comment by mads-hartmann** [comment]
Ah okay. Nice to know that what I'm doing isn't completely out there :) 

/Mads

**Comment by holdenk** [comment]
Support has been added. I'll update the docs soon :)

**Comment by mads-hartmann** [comment]
Very awesome! Thanks!

**Comment by mads-hartmann** [comment]
If you could ping me here once you have a new version online that would be great.

**Comment by holdenk** [comment]
It is now in 0.9.14 , just override "core" in your model to be Some("coreName"). It should be synced to the central maven in an hour or two.

**Comment by mads-hartmann** [comment]
Thanks!

**Comment by mads-hartmann** [comment]
It works like a charm btw.
